######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 8 15:39:24 2013
######################################################################

TEMPLATE = subdirs
TARGET = bmail
DEPENDPATH += . src headers
INCLUDEPATH += . src headers

# Input

HEADERS += 

SOURCES += src/main.cpp
